---
version: 2
plan:
  project-key: CL
  key: VLUR
  name: VpnLibs - Upload Conan Recipes
stages:
  - Default Stage:
      manual: false
      final: false
      jobs:
        - Default Job
Default Job:
  key: JOB1
  docker:
    image: adguard/core-libs:2.6
    docker-run-arguments: [ ]
  tasks:
    - !include docker-clean.yaml
    - checkout:
        force-clean-build: 'true'
        description: Checkout
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -x
            set -e

            python3 -m pip install conan --upgrade

            # Clean up local cache
            conan remove -c "*"

            conan remote add --index 0 art ${bamboo.conanRepoUrl} || true

            cp ./bamboo-specs/scripts/conan_upload_and_cleanup.sh ./scripts/
            python3 -m pip install -r ./scripts/requirements.txt
            ./scripts/conan_export.py

            ./scripts/conan_upload_and_cleanup.sh
  final-tasks:
    - script:
        interpreter: SHELL
        scripts:
          - |-
            # Clean up
            conan remove -c "*"
        description: Clean up
  requirements:
    - adg-privileged-docker
  artifact-subscriptions: [ ]
repositories:
  - core-libs/vpn-libs:
      scope: global
branches:
  create: manually
  delete: never
  link-to-jira: true
triggers: [ ]
notifications: [ ]
labels: [ ]
other:
  concurrent-build-plugin: system-default
