---
version: 2
plan:
  project-key: CL
  key: VLUR
  name: VpnLibs - Upload Conan Recipes
stages:
  - Default Stage:
      manual: false
      final: false
      jobs:
        - Default Job
Default Job:
  key: JOB1
  docker:
    image: adguard/core-libs:latest
    volumes:
      ${bamboo.git.cache.directory}: ${bamboo.git.cache.directory}
      ${system.HOME}/.ssh: /root/.ssh
    docker-run-arguments: [ ]
  tasks:
    - !include docker-clean.yaml
    - checkout:
        force-clean-build: 'true'
        description: Checkout
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -e
            git remote set-url origin ${bamboo_planRepository_repositoryUrl}
            git pull
            git reset
            conan remove -f '*'
            conan remote add -i 0 art ${bamboo.conanRepoUrl} || true
            python3 -m pip install -r ./scripts/requirements.txt
            ./scripts/conan_export.py
            conan user -p "${bamboo_artifactoryPassword}" -r art "${bamboo_artifactoryUser}" > upload.txt 2>&1
            conan upload -r art --all -c '*' >> upload.txt 2>&1
  final-tasks:
    - script:
        interpreter: SHELL
        scripts:
          - |-
            # Clean up
            conan remove -f '*'
            conan remove --locks
        description: Clean up
  requirements:
    - adg-privileged-docker
  artifact-subscriptions: [ ]
repositories:
  - core-libs/vpn-libs:
      scope: global
branches:
  create: manually
  delete: never
  link-to-jira: true
triggers: [ ]
notifications: [ ]
labels: [ ]
other:
  concurrent-build-plugin: system-default
